/* ================= GLOBAL CONFIG ================= */
const MARKUP = 1.01; // naik 1% khusus TOP UP

const eventSystem = {
  active: true,
    start: "2026-02-17 10:00",
      end:   "2027-02-17 14:00",
        text: "MASIH MAINTANCE YA GENDENG",
          discountTopup: 0.05, // 5%
            discountJoki: 0      // 0%
            };

            /* ================= DOM ================= */
            const slider = document.getElementById("slider");

            /* ================= STATE ================= */
            let currentPage = 0;
            let prevPage = 0;
            let selectedPayment = "";

            let order = {};
            let joki = { type: "", price: 0, qty: 1 };

            /* ================= DATA ================= */
            const data = {
              "Free Fire": [
                  ["140 Diamonds",16415],["720 Diamonds",81579],["70 Diamonds",8220],
                      ["100 Diamonds",10370],["510 Diamonds",59555],["1080 Diamonds",123700],
                          ["210 Diamonds",24555],["5 Diamonds",768],["1075 Diamonds",122550],
                              ["355 Diamonds",40925],["12 Diamonds",1649],["25 Diamonds",3799],
                                  ["50 Diamonds",5190],["53 Diamonds",5970],["64 Diamonds",8220],
                                      ["127 Diamonds",14970],["323 Diamonds",38025],["350 Diamonds",40990],
                                          ["645 Diamonds",75365],["655 Diamonds",76920],["925 Diamonds",106553],
                                              ["1200 Diamonds",137250],["1285 Diamonds",147600],["1450 Diamonds",164600],
                                                  ["1800 Diamonds",205700],["1875 Diamonds",213953],["1973 Diamonds",226400],
                                                      ["2000 Diamonds",228277],["2160 Diamonds",245900],["2180 Diamonds",246926],
                                                          ["2200 Diamonds",250099],["2400 Diamonds",273113],["3309 Diamonds",376364],
                                                              ["3600 Diamonds",410500],["3640 Diamonds",411304],["3800 Diamonds",431079],
                                                                  ["4000 Diamonds",453324],["4450 Diamonds",505083],["4800 Diamonds",545400],
                                                                      ["6480 Diamonds",736395],["6900 Diamonds",786900],["7290 Diamonds",824321],
                                                                          ["9800 Diamonds",1109508],["36500 Diamonds",4138380],["73100 Diamonds",8200000]
                                                                            ],

                                                                              "Mobile Legends": [
                                                                                  ["3 Diamonds",1054],["5 Diamonds",1439],["10 Diamonds",2929],
                                                                                      ["12 Diamonds",3349],["14 Diamonds",4000],["18 Diamonds",5200],
                                                                                          ["19 Diamonds",5270],["28 Diamonds",7460],["36 Diamonds",9987],
                                                                                              ["44 Diamonds",9990],["59 Diamonds",13790],["74 Diamonds",17400],
                                                                                                  ["85 Diamonds",20090],["170 Diamonds",38980],["222 Diamonds",51000],
                                                                                                      ["240 Diamonds",52980],["296 Diamonds",67980],["370 Diamonds",84980],
                                                                                                          ["408 Diamonds",92980],["568 Diamonds",129980],["875 Diamonds",204980],
                                                                                                              ["966 Diamonds",218980],["2010 Diamonds",444980],["4830 Diamonds",1129980]
                                                                                                                ],

                                                                                                                  "Arena Breakout": [
                                                                                                                      ["60+6 Bonds",16180],["310+25 Bonds",80200],["630+45 Bonds",158250],
                                                                                                                          ["1580+110 Bonds",388130],["3200+200 Bonds",771190],
                                                                                                                              ["6500+320 Bonds",1501150],
                                                                                                                                  ["Composite Case (30 days)",110040],
                                                                                                                                      ["Bulletproof Case (30 days)",37610],
                                                                                                                                          ["Beginner Select",12510],
                                                                                                                                              ["Advanced Battle Pass",63550],
                                                                                                                                                  ["Premium Battle Pass",178290]
                                                                                                                                                    ],
                                                                                                                                                    "Roblox": [ 
                                                                                                                                                    ["100 Robux(5 HARI)" ,38]
                                                                                                                                                    ]
                                                                                                                                                    };

                                                                                                                                                    /* ================= EVENT CHECK ================= */
                                                                                                                                                    function isEventActive() {
                                                                                                                                                      if (!eventSystem.active) return false;

                                                                                                                                                        const now = Date.now();
                                                                                                                                                          const start = new Date(eventSystem.start.replace(" ", "T")).getTime();
                                                                                                                                                            const end = new Date(eventSystem.end.replace(" ", "T")).getTime();

                                                                                                                                                              return now >= start && now <= end;
                                                                                                                                                              }

                                                                                                                                                              /* ================= PRICE ENGINE (SATU PINTU) ================= */
                                                                                                                                                              function getFinalPrice(basePrice, type) {
                                                                                                                                                                let total = basePrice;

                                                                                                                                                                  // markup TOP UP
                                                                                                                                                                    if (type === "TOPUP") {
                                                                                                                                                                        total *= MARKUP;
                                                                                                                                                                          }

                                                                                                                                                                            // event discount
                                                                                                                                                                              if (isEventActive()) {
                                                                                                                                                                                  if (type === "TOPUP") {
                                                                                                                                                                                        total -= total * eventSystem.discountTopup;
                                                                                                                                                                                            }
                                                                                                                                                                                                if (type === "JOKI") {
                                                                                                                                                                                                      total -= total * eventSystem.discountJoki;
                                                                                                                                                                                                          }
                                                                                                                                                                                                            }

                                                                                                                                                                                                              return Math.round(total);
                                                                                                                                                                                                              }

                                                                                                                                                                                                              /* ================= SLIDER ================= */
                                                                                                                                                                                                              function goTo(i) {
                                                                                                                                                                                                                document.querySelectorAll(".page").forEach((p, idx) => {
                                                                                                                                                                                                                    p.classList.toggle("active", idx === i);
                                                                                                                                                                                                                      });
                                                                                                                                                                                                                        slider.style.transform = `translateX(-${i * 100}vw)`;
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                        /* ================= TOP UP ================= */
                                                                                                                                                                                                                        function openNominal(game) {
                                                                                                                                                                                                                          document.getElementById("gameTitle").innerText = game;
                                                                                                                                                                                                                            const grid = document.getElementById("nominalGrid");
                                                                                                                                                                                                                              grid.innerHTML = "";

                                                                                                                                                                                                                                data[game].forEach(([nominal, harga]) => {
                                                                                                                                                                                                                                    const card = document.createElement("div");
                                                                                                                                                                                                                                        card.className = "card";
                                                                                                                                                                                                                                            card.innerHTML = `
                                                                                                                                                                                                                                                  <div class="nominal-text">${nominal}</div>
                                                                                                                                                                                                                                                        <small>Rp ${harga.toLocaleString("id-ID")}</small>
                                                                                                                                                                                                                                                            `;

                                                                                                                                                                                                                                                                card.onclick = () => {
                                                                                                                                                                                                                                                                      const total = getFinalPrice(harga, "TOPUP");

                                                                                                                                                                                                                                                                            order = {
                                                                                                                                                                                                                                                                                    type: "TOPUP",
                                                                                                                                                                                                                                                                                            game,
                                                                                                                                                                                                                                                                                                    nominal,
                                                                                                                                                                                                                                                                                                            total
                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                        document.getElementById("orderInfo").innerText =
                                                                                                                                                                                                                                                                                                                                `Top Up ${game}\n${nominal}\nTotal: Rp ${total.toLocaleString("id-ID")}`;

                                                                                                                                                                                                                                                                                                                                      selectedPayment = "";
                                                                                                                                                                                                                                                                                                                                            prevPage = 1;
                                                                                                                                                                                                                                                                                                                                                  goTo(3);
                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                          grid.appendChild(card);
                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                              goTo(1);
                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                              /* ================= JOKI ================= */
                                                                                                                                                                                                                                                                                                                                                              function selectJoki(el, type, price) {
                                                                                                                                                                                                                                                                                                                                                                document.querySelectorAll(".joki-item").forEach(i => i.classList.remove("active"));
                                                                                                                                                                                                                                                                                                                                                                  el.classList.add("active");

                                                                                                                                                                                                                                                                                                                                                                    joki = { type, price, qty: 1 };
                                                                                                                                                                                                                                                                                                                                                                      document.getElementById("qty").innerText = 1;
                                                                                                                                                                                                                                                                                                                                                                        updateJokiTotal();
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        function plusQty() {
                                                                                                                                                                                                                                                                                                                                                                          joki.qty++;
                                                                                                                                                                                                                                                                                                                                                                            document.getElementById("qty").innerText = joki.qty;
                                                                                                                                                                                                                                                                                                                                                                              updateJokiTotal();
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                              function minusQty() {
                                                                                                                                                                                                                                                                                                                                                                                if (joki.qty > 1) {
                                                                                                                                                                                                                                                                                                                                                                                    joki.qty--;
                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("qty").innerText = joki.qty;
                                                                                                                                                                                                                                                                                                                                                                                            updateJokiTotal();
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                              function updateJokiTotal() {
                                                                                                                                                                                                                                                                                                                                                                                                const total = getFinalPrice(joki.price * joki.qty, "JOKI");
                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById("totalHarga").innerText =
                                                                                                                                                                                                                                                                                                                                                                                                      "Rp " + total.toLocaleString("id-ID");
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                      function goPaymentJoki() {
                                                                                                                                                                                                                                                                                                                                                                                                        if (!joki.type) return alert("Pilih joki dulu");

                                                                                                                                                                                                                                                                                                                                                                                                          const total = getFinalPrice(joki.price * joki.qty, "JOKI");

                                                                                                                                                                                                                                                                                                                                                                                                            order = {
                                                                                                                                                                                                                                                                                                                                                                                                                type: "JOKI",
                                                                                                                                                                                                                                                                                                                                                                                                                    joki: joki.type,
                                                                                                                                                                                                                                                                                                                                                                                                                        qty: joki.qty,
                                                                                                                                                                                                                                                                                                                                                                                                                            total
                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById("orderInfo").innerText =
                                                                                                                                                                                                                                                                                                                                                                                                                                    `Joki ${joki.type}
                                                                                                                                                                                                                                                                                                                                                                                                                                    Jumlah: ${joki.qty}
                                                                                                                                                                                                                                                                                                                                                                                                                                    Total: Rp ${total.toLocaleString("id-ID")}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                      selectedPayment = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                        prevPage = 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                          goTo(3);
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                          /* ================= PAYMENT ================= */
                                                                                                                                                                                                                                                                                                                                                                                                                                          document.addEventListener("click", e => {
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!e.target.classList.contains("card")) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!e.target.closest(".payment")) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                document.querySelectorAll(".payment .card")
                                                                                                                                                                                                                                                                                                                                                                                                                                                    .forEach(c => c.classList.remove("active"));

                                                                                                                                                                                                                                                                                                                                                                                                                                                      e.target.classList.add("active");
                                                                                                                                                                                                                                                                                                                                                                                                                                                        selectedPayment = e.target.innerText.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* ================= WHATSAPP ================= */
                                                                                                                                                                                                                                                                                                                                                                                                                                                        function sendWA() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const id = document.getElementById("userId").value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!id) return alert("Masukkan ID / Server");
                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!selectedPayment) return alert("Pilih payment");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                let msg = `ORDER RXM\n\n`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (order.type === "TOPUP") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      msg +=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `Top Up
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Game: ${order.game}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Nominal: ${order.nominal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Total: Rp ${order.total.toLocaleString("id-ID")}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (order.type === "JOKI") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              msg +=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `Joki
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Jenis: ${order.joki}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Jumlah: ${order.qty}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Total: Rp ${order.total.toLocaleString("id-ID")}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  msg += `\nPayment: ${selectedPayment}\nID: ${id}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    window.open(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "https://wa.me/6285782872735?text=" + encodeURIComponent(msg),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /* ================= PROMO TEXT ================= */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.addEventListener("DOMContentLoaded", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const promo = document.querySelector(".promo-text");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (isEventActive()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      promo.innerText = eventSystem.text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            promo.parentElement.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /* ================= COUNTDOWN ================= */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function startCountdown() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const el = document.getElementById("countdown");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!isEventActive()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            el.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const end = new Date(eventSystem.end.replace(" ", "T")).getTime();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const diff = end - Date.now();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (diff <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        el.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const h = Math.floor(diff / (1000 * 60 * 60));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const m = Math.floor((diff / (1000 * 60)) % 60);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const s = Math.floor((diff / 1000) % 60);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  el.style.display = "block";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      el.innerText = `⏳ EVENT BERAKHIR ${h}j ${m}m ${s}d`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 1000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.addEventListener("DOMContentLoaded", startCountdown);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* ================= INIT ================= */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        goTo(0);